In [1]:
import duckdb
import pandas as pd
import numpy as np

In [68]:
db = duckdb.connect('publications.db')

In [69]:
db.sql("SHOW TABLES")

┌─────────────────────────┐
│          name           │
│         varchar         │
├─────────────────────────┤
│ publications_classified │
│ publications_embedding  │
│ run_260617_1048         │
│ run_260617_1048_reverse │
│ run_260617_1339         │
│ run_260617_1339_reverse │
└─────────────────────────┘

In [ ]:
#db.sql("DROP TABLE run_260616_1604")

In [70]:
#db.sql("DESCRIBE run_260617_1048")
db.sql("DESCRIBE publications_classified")

┌────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬─────────┬─────────┬─────────┐
│      column_name       │                                                                                                   column_type                                                                                                    │  null   │   key   │ default │  extra  │
│        varchar         │                                                                                                     varchar                                                                                                      │ varchar │ varchar │ varchar │ varchar │
├────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────┼─────────┼─────────┼─────────┤
│ id                     │ VARCHAR                                                                                                                                                                                                          │ YES     │ NULL    │ NULL    │ NULL    │
│ title                  │ VARCHAR                                                                                                                                                                                                          │ YES     │ NULL    │ NULL    │ NULL    │
│ abstract               │ VARCHAR                                                                                                                                                                                                          │ YES     │ NULL    │ NULL    │ NULL    │
│ authors                │ STRUCT(affiliations MAP(VARCHAR, VARCHAR)[], corresponding VARCHAR, current_organization_id VARCHAR, first_name VARCHAR, last_name VARCHAR, orcid VARCHAR[], raw_affiliation VARCHAR[], researcher_id VARCHAR)[] │ YES     │ NULL    │ NULL    │ NULL    │
│ concepts_relevant      │ VARCHAR[]                                                                                                                                                                                                        │ YES     │ NULL    │ NULL    │ NULL    │
│ date                   │ VARCHAR                                                                                                                                                                                                          │ YES     │ NULL    │ NULL    │ NULL    │
│ funder_countries       │ STRUCT(id VARCHAR, "name" VARCHAR)[]                                                                                                                                                                             │ YES     │ NULL    │ NULL    │ NULL    │
│ funders                │ VARCHAR                                                                                                                                                                                                          │ YES     │ NULL    │ NULL    │ NULL    │
│ open_access            │ VARCHAR[]                                                                                                                                                                                                        │ YES     │ NULL    │ NULL    │ NULL    │
│ research_org_cities    │ STRUCT(id VARCHAR, "name" VARCHAR)[]                                                                                                                                                                             │ YES     │ NULL    │ NULL    │ NULL    │
│ research_org_countries │ STRUCT(id VARCHAR, "name" VARCHAR)[]                                                                                                                                                                             │ YES     │ NULL    │ NULL    │ NULL    │
│ research_org_names     │ VARCHAR[]                                                                                                                                                                                                        │ YES     │ NULL    │ NULL    │ NULL    │
│ times_cited            │ BIGINT                                                                                                                                                                                                           │ YES     │ NULL    │ NULL    │ NULL    │
│ type                   │ VARCHAR                                                                                                                                                                                                          │ YES     │ NULL    │ NULL    │ NULL    │
│ year                   │ BIGINT                                                                                                                                                                                                           │ YES     │ NULL    │ NULL    │ NULL    │
│ journal.id             │ VARCHAR                                                                                                                                                                                                          │ YES     │ NULL    │ NULL    │ NULL    │
│ journal.title          │ VARCHAR                                                                                                                                                                                                          │ YES     │ NULL    │ NULL    │ NULL    │
│ pred_combined          │ VARCHAR                                                                                                                                                                                                          │ YES     │ NULL    │ NULL    │ NULL    │
│ pred_pillar            │ VARCHAR                                                                                                                                                                                                          │ YES     │ NULL    │ NULL    │ NULL    │
└────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┴─────────┴─────────┴─────────┘
  19 rows                                                                                                                                                                                                                                                                 6 columns

In [62]:
df = db.sql("SELECT * FROM publications_embedding").df()
#df = db.sql("SELECT * FROM publications_classified").df()

In [63]:
len(df)

1055

In [67]:
df

                  id                                         embeddings
0     pub.1188588536  [0.31289476, -0.09961835, -0.21389598, 0.37632...
1     pub.1185255386  [1.1885281, 0.61516505, -0.0695103, 0.02542673...
2     pub.1187762379  [1.2824916, 0.63336486, -0.29047644, 0.0556157...
3     pub.1182803126  [0.57183164, 0.34620082, 0.45478332, -0.093721...
4     pub.1194716889  [0.41298577, 0.27710178, -0.23516482, -0.14550...
...              ...                                                ...
1050  pub.1196042162  [0.24065934, 1.4526184, -0.17821333, 0.6593842...
1051  pub.1196038085  [1.2808062, 0.3774147, -0.14655226, 0.20098786...
1052  pub.1196035716  [-0.56777155, -0.89472115, 0.30029488, 1.70841...
1053  pub.1196032121  [0.93821347, 0.6671621, 0.23909798, 0.00030668...
1054  pub.1196023851  [-0.28822348, 0.13153942, -0.016149275, -0.353...

[1055 rows x 2 columns]

In [ ]:
db.sql("SELECT * FROM data_run_test").df()

1085

In [29]:
db.sql("SELECT * FROM publications_embedding").df()

                  id                                         embeddings
0     pub.1190504216  [1.2145487, 0.7846523, -0.39498022, -0.2221686...
1     pub.1196389069  [0.52091134, 0.5584732, -0.6283343, -0.4086755...
2     pub.1196320432  [1.1825451, 0.47879434, -0.26228788, 0.0428953...
3     pub.1189115195  [0.6792192, -0.49684674, -0.6420987, 0.4886556...
4     pub.1195599811  [0.687109, -1.2782173, 0.13125606, 0.8823242, ...
...              ...                                                ...
1080  pub.1195503534  [1.2857035, 0.0034655854, -0.24009885, 0.18280...
1081  pub.1195498149  [0.93019027, 0.6092237, -0.24329598, -0.216328...
1082  pub.1195486018  [0.7835876, -0.98454076, -0.2740623, 1.1459801...
1083  pub.1195485113  [1.2619324, 2.1056752, -1.3297355, 0.16934939,...
1084  pub.1195483455  [1.1265651, -0.012746349, 1.1739706, 0.1274480...

[1085 rows x 2 columns]

In [71]:
db.close()