In [1]:
import duckdb
import pandas as pd
import numpy as np
from rapidfuzz import process, fuzz, utils

In [2]:
db = duckdb.connect('patents.db')
db.execute("PRAGMA memory_limit='3GB'")
db.execute("PRAGMA temp_directory='C:/temp/duckdb_spill'")
db.execute("PRAGMA threads=2")

In [3]:
db.close()

In [3]:
db.sql("SHOW TABLES")

┌─────────────────────────┐
│          name           │
│         varchar         │
├─────────────────────────┤
│ patents_classified      │
│ patents_embeddings      │
│ patents_labelled        │
│ run_260710_0000         │
│ run_260710_0000_reverse │
└─────────────────────────┘

In [4]:
#db.sql("DESCRIBE run_260617_1048")
db.sql("DESCRIBE patents_labelled")

┌────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│    column_name     │ column_type │  null   │   key   │ default │  extra  │
│      varchar       │   varchar   │ varchar │ varchar │ varchar │ varchar │
├────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id                 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ family_id          │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ application_number │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ title              │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ abstract           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ cpc                │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ publication_year   │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ jurisdiction       │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ date_dimensions    │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ date_ML            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ date_LLM           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ scope_curated      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ pillar_curated     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ date_labelled      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ research_category  │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ end_product        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ ingredient         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
  17 rows                                                        6 columns

In [51]:
#df = db.sql("SELECT * FROM publications_embedding").df()
df = db.sql("SELECT * FROM patents_labelled").df()

In [6]:
df

,id,family_id,application_number,title,abstract,cpc,publication_year,jurisdiction,date_dimensions,date_ML,date_LLM,scope_curated,pillar_curated,date_labelled,research_category,end_product,ingredient
0,KR-20260058202-A,87847814,KR1020267005189,Powdered food emulsion composition containing ...,The present invention relates to a powdered fo...,"['A23P10/40', 'A23L2/39', 'A23C11/06', 'A23C11...",2026,KR,260710,260710,260710,in,PB,260710,End product formulation,Cross-cutting,"Emulsions, gels, and binders"
1,WO-2025074118-A1,93119608,GB2024/052562,METHODS FOR INCREASING THE FAT CONTENT OF A CELL,Described herein are novel methods for increas...,"['C12N5/0653', 'C12N2501/01', 'C12N2527/00']",2025,WO,260710,260710,260710,in,CM,260710,Cell line development,Meat,Fats and oils
2,EP-4638706-A2,89542141,EP23838012.5,NANOFIBROUS SCAFFOLD FOR CELL CULTURING,The present invention relates to a method for ...,"['C12N2513/00', 'C12M33/00', 'C12M25/02', 'C12...",2025,EP,260710,260710,260710,in,CM,260710,Scaffolding,Agnostic,N/A
3,PL-247657-B1,91227479,PL442891,Method for producing instant vegetable steaks ...,The subject of the application is an instant v...,"['A23L19/00', 'A23L33/125', 'A23L33/105', 'A23...",2025,PL,260710,260710,260710,in,PB,260710,End product formulation,Meat,N/A
4,US-20250000129-A1,83692816,US18690539,USE OF LEGUMINOUS STARCH AND ITS CROSS LINKED ...,The present invention is relative to the use o...,"['A23L29/219', 'A23L13/426', 'A23J3/227', 'A23...",2025,US,260710,260710,260710,in,PB,260710,End product formulation,Meat,"Emulsions, gels, and binders"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,WO-2022136708-A1,74105752,EP2021/087661,PRODUCTION OF FUNGAL BIOMASS,The present invention relates to a method for ...,"[Y02E50/10, A23L31/00, A23J3/20, C12N1/22, A23...",2022,WO,260710,260710,260710,in,F,260710,Feedstocks,Agnostic,N/A
446,WO-2022103318-A1,78695771,SE2021/051128,A GENETICALLY MODIFIED YEAST CELL FOR HEMOGLOB...,"A genetically modified yeast cell, wherein the...","[C12N2510/00, C07K14/395, C12N15/81, C12R2001/...",2022,WO,260710,260710,260710,in,F,260710,Target molecule selection,Meat,N/A
447,WO-2022058287-A1,74095986,EP2021/075137,"A MICROBIAL CELL PRODUCT, METHOD FOR OBTAINING...",The present invention relates to a method for ...,"[A23J3/225, A23J3/227, A23L33/145, A23L33/135,...",2022,WO,260710,260710,260710,in,F,260710,Ingredient optimisation,Eggs and egg proteins,"Emulsions, gels, and binders"
448,WO-2021104846-A1,73059967,EP2020/081588,POWDERED COMPOSITION COMPRISING A SOLID PLANT-...,The present disclosure relates to a powdered c...,"[A23K20/158, A23D7/05, A23D9/00, A23L29/10, A2...",2021,WO,260710,260710,260710,in,PB,260710,Ingredient optimisation,Meat,Fats and oils
449,ZA-201705146-B,52673981,ZA2017/05146,EDIBLE FUNGI,NaN,"[A23L13/426, A23L33/175, A23J1/00, A23V2002/00...",2019,ZA,260710,260710,260710,in,F,260710,Other,Agnostic,N/A

In [6]:
# clean abstract
df['abstract'] = df['abstract'].str.replace(r'<[^>]*>', '', regex=True)

In [40]:
company_list = pd.read_csv("company_list.csv")
company_database = pd.read_csv("company_database.csv")

companies = pd.concat([company_list['Cleaned-up Name'], company_database['Company']]).drop_duplicates().tolist()

In [50]:
companies

['21st.BIO',
 '70/30 Food Tech',
 'Adamo Foods',
 'Aerbio (Deep Branch)',
 'Agro Ludens',
 'ÄIO',
 'Air Protein',
 'Algama',
 'Algenuity',
 'Algrow Biosciences',
 'All G',
 'Allium Bio',
 'Almendra',
 'Alver',
 'Amai Proteins',
 'Angel Yeast',
 'Aqua Cultured Foods',
 'Ark Biotech',
 'Arkeon Biotechnologies',
 'Asahi Group',
 'Asterix Foods',
 'Balletic Foods',
 'Beijing Technology and Business University',
 'Better Dairy',
 'Better Meat Company',
 'Better Nature Ltd',
 'betterland foods',
 'Bevo Biotehnoloske Resitve doo',
 'Biofect Innovations',
 'BK GIULINI GMBH',
 'Blue Canopy',
 'Bolder Foods',
 'Bond Pet Foods',
 'Bosque Foods',
 'Brevel',
 'Brig Bio',
 'C&dac',
 'c16 Biosciences',
 'Calidris Bio',
 'Calysta',
 'Cargill Food Ingredients',
 'Cassius AB',
 'catchfree',
 'Central South University of Forestry and Technology (China)',
 'Change Foods',
 'Changing Bio',
 'Checkerspot',
 'China Meat Research Centre',
 'CHUNG JAE WOOK',
 'Chunk Foods',
 'Circe Biotech',
 'CJ CheilJedang',
 'Clean Food Group',
 'Corbion',
 'Cosun Protein',
 'Court Ltd AB',
 'Cultivated Biosciences',
 'Cura Global Health BVI Ltd',
 'Daesang',
 'DairyX',
 'Daisy Lab',
 'De Novo FoodLabs',
 'DMK Deutsches Milchkontor GmbH',
 'Done Properly',
 'DSM-Firmenich',
 'DTU',
 'Dupont Nutrition & Health',
 'Ecovative',
 'Eden Brew',
 'Edonia',
 'Eggmented Reality',
 'Eighth Day Foods',
 'Emmay',
 'Enifer',
 'ENOUGH',
 'Equii (Cella Farms)',
 'Esencia Foods',
 'Eternal',
 'EVERY',
 'Farmless',
 'Fender Group',
 'FermentationExperts',
 'Fermify',
 'Fermtech',
 'FOOD INDUSTRY RESEARCH AND DEVELOPMENT INSTITUTE',
 'Fooditive Group',
 'Foreverbio Innovations',
 'Formo',
 'FUNKI',
 'Future Cow',
 'Fybraworks Foods',
 'Gadot Biochemical',
 'Geltor',
 'Givaudan',
 'Gongju National University Industry-Academia Cooperation Foundation',
 'Green Spot Technologies',
 'Guangzhou Bioform Biotechnology Co ltd; South China Agricultural University',
 'gyeonggi-do',
 'Hanwha Solutions Corp',
 'Hefei University of Technology',
 'Helaina',
 'Hochland',
 'Houdek',
 'Houdek  ',
 'Hubei Nine Court Of Biological Science And Technology Development LLC',
 'Hyfe Foods',
 'IFF (International Flavors & Fragrances)',
 'Imagindairy',
 'Impossible Foods',
 'Infinite Roots',
 'Ingrediome',
 'Innocent Meat',
 'Innomy',
 'INTAKE',
 'Ironic Biotech',
 'Jiangnan University',
 'Jiangxi Fushine Biotechnology',
 'Jooules',
 'KAIST',
 'Kangma Healthcode Shanghai Biotech Co Ltd',
 'Kikkoman Corp',
 'Kongju National Univeristy',
 'Kontor N GmbH',
 'Koralo',
 'Korea University Research and Business Foundation',
 'KUBARA SPOLKA Z OGRANICZONA ODPOWIEDZIALNOSCIA',
 'Kuehnle Agrosystems',
 'Kynda Biotech',
 'La Revolution Champignon SAS',
 'Lanjia Biotechnology Co ltd',
 'Lanzatech NZ Inc',
 'Levur ',
 'Libre Foods',
 'LIVEKINDLY Collective',
 'Liven Proteins',
 'Luya',
 'Luyef Biotechnologies',
 'Maash',
 'Maia Farms',
 'Marlow Ingredients',
 'Mati Foods',
 'MATR Foods',
 'Meati',
 'The Mediterranean Food Lab (MFL)',
 'Meeat',
 'Melt&Marble',
 'Meridian Biotech',
 'Michroma',
 'MicroHarvest',
 'Microo Food Ingredients SL',
 'Millow',
 'Mitsubishi International Food Ingredients',
 'Moa Biotech',
 'MOA Foodtech',
 'Mooji Meats',
 'MOONLAB Foods',
 'More Alternative Foods Ltd',
 'More Foods Innotech',
 'More Meat',
 'Motif Foodworks',
 'Muu',
 'Myco4Food',
 'Mycofeast',
 'MycoHoldings',
 'MycoTechnology',
 'Mycovation',
 'Myoworks',
 'Mycsology',
 'MyForest Foods',
 'Mynu Corp',
 'Nanjing Normal University',
 'Naplasol',
 'Natural Resources Institute Finland',
 "Nature's Fynd",
 'Nestlé',
 'New Culture',
 'New School Foods',
 'New Singularity',
 'Newmilkbuzz BV',
 'Nextferm Tech',
 'Noblegen',
 'NoMy',
 'NoPalm Ingredients',
 'Nosh.bio',
 'Nourish Ingredients',
 'NovaMeat',
 'Novonesis',
 'NovoNutrients',
 'Nuoshi Bio',
 'Nurasa',
 'Nutrition from Water',
 'Nutritional Ingredients Private Ltd',
 'Nutropy',
 'Nutrumami',
 'Odontella',
 'ODS Protein',
 'Ohayo Valley',
 'Ohly',
 'Omaiko',
 'Onego Bio',
 'Onima',
 'Oobli',
 'Optimized Foods',
 'Organo Food Tech Corp',
 'Otro Bio',
 'paleo',
 'Pario Corp',
 'Perfect Day',
 'Phycom',
 'Phytolon',
 'Phyx44 Labs ',
 'Planeat',
 'Planetarians',
 'Planetary',
 'Planted Foods',
 'Plantopia',
 'Pleurette',
 'PoLoPo',
 'Poseidona',
 'Pow.bio',
 'Power to Protein',
 'PreFer Industries',
 'Prime Roots',
 'Procter and Gamble Co',
 'Promyc (Mycorena)',
 'The Protein Brewery',
 'Proteins of Tomorrow',
 'Pullulo',
 'Purac Biochem BV',
 'PURETURE',
 'Quazy Foods',
 'Red River Innovations',
 'ReMilk',
 'Remilk',
 'ReNewFood',
 'Republic of Korea: Rural Dev Adm',
 'Revyve',
 'Rewild Bio',
 'Rim Corp',
 'Section Hansen Co ltd',
 'Shaanxi University of Science and Technology',
 'Shinsegae Food',
 'Shiru',
 'SifoTEK',
 'SimpliiGood',
 'Smallfood',
 'Solar Foods',
 "Sophie's BioNutrients",
 'South China Agricultural University',
 'Soyou F&B Co., Ltd.',
 'Spread Co Ltd',
 'Standard Oil Co',
 'Standing Ovation',
 'Stichting Eco Consult',
 'String Bio',
 'SUJIS LINK',
 'Sun Bear Biofuture',
 'Sun Food Co Ltd',
 'Superbrewed Food',
 'SUPERHUMN',
 'Supreme',
 'Sutuo Technology Beijing Co',
 'Synbio Technologies',
 'Tablemark Co Ltd',
 'Technical University Munich',
 'Tempty Foods',
 'Terraferma Foods',
 'The Cultivated B',
 'ProteinDistillery',
 'THIS',
 'Those Vegan Cowboys',
 'Tianjin Meilian Food Co ltd',
 'Tianjin University of Commerce',
 'Triton Algae Innovations',
 'TurtleTree',
 'Typcal',
 'ULTIMEAT',
 'Ummino',
 'UniBio',
 'Unilever',
 'Universidad de Valladolid',
 'Updairy',
 'Vegout Fungi Ltd',
 'Verley',
 'Viridos Inc',
 'Vivici',
 'Voyage Foods Incorporated',
 'VTT',
 'Walding Foods ',
 'WeMeet',
 'Wholesome Savor',
 'Wild Earth',
 'Wuxi Yiyu Technology Development Co Ltd',
 'Yali Bio',
 'Yang Ju-seok',
 'Yeap',
 'Yeastup',
 'Yemoja',
 'Zero Acre',
 'Zero Cow Factory',
 'Zhejiang University ZJU',
 'StrainX Bioworks',
 '[Mock]',
 '1.5 Degree',
 '1Ness Foods',
 '3D Bio-Tissues',
 '4U Free From',
 '5YES!',
 '8th Continent',
 '15/16 Group',
 '50/50 Foods',
 'A tal da Castanha',
 'A-Life Corp.',
 'A.H.A International Co.',
 'A&B Ingredients',
 'AAK',
 'Aardaia',
 'AB Mauri',
 "Abbot's",
 'AbbVie',
 'Aber Instruments',
 'ABERYNE',
 'Above Food',
 'acayù',
 'Accellta',
 'AcerChem International Inc.',
 'Acetar',
 'Acme Food Sales',
 'Açougue Vegano',
 'Actual Veggies',
 'Adamjee Lukmanjee & Sons',
 'Adaptyv Bio',
 'AdeS',
 'ADM (Archer Daniels Midland)',
 'Adolf Kühner AG',
 'Advanced Instruments Ltd',
 'Advanced Protein Technologies Corp.',
 'Afineur',
 'AGC Biologics',
 'Agile BioFoundry',
 'Agrenvec',
 'Agricultural Utilization Research Institute',
 'AgriFoodTrade',
 'Agrocorp',
 'AGT Foods',
 'Agulos Biotech',
 'AH Terra',
 'Ahimsa Bio',
 'Ahimsa Companies',
 'Airon Sabor e Saude',
 'Aivia',
 'Ajinomoto',
 'Alagene',
 'Alberta Food Centre',
 'alberts',
 'Alcheme Bio',
 "Alden's Organic Ice Cream",
 'Aleph Farms',
 'Alfa Chilena S.A.',
 'Alfa-Ruby',
 "alfred's",
 'ALGAPHARMA BIOTECH CORP.',
 'AlgiSys',
 'Alimentos Sanygran',
 'Alinor',
 'All Organic Treasures',
 'All Vegetarian Inc. ',
 "All Y'alls Foods",
 'Allbiotech',
 'Allmicroalgae',
 'Allozymes',
 'Almance Foods ',
 'Alphorn Venture Partners',
 'Alpine Bio',
 'Alpro',
 'AlProtein',
 'Alt Atlas',
 'ALT Co.',
 'Alt Milk',
 'ALTCo',
 'Alternative Proteins Innovation Center',
 'Alternative Stores',
 'ALTist',
 'ALTN',
 'Altro Food',
 'Amandín',
 'Amano Enzymes',
 'Amazonika Mundi',
 'Ambrosia Sciences',
 'Amêndoas do Brasil',
 'América Pampa',
 'American Laboratories',
 'American Sorghum',
 'Amica Natura',
 "Amy's Kitchen",
 'aMYLK',
 'Anamma Foods',
 'Anchor Ingredients',
 'Ancrée',
 'Andean Naturals',
 'ANDFOODS',
 'Andros',
 'Angel Food',
 'Annora Alimentos',
 'Anomaly Bio ',
 'ANPOLY',
 'Anthology',
 'Ants Innovate',
 'Aoste',
 'Aphrodite Global Ingredients',
 'Aquafarmtory',
 'Arbiom',
 'Arborea',
 'Arche',
 'Archway Pet Food',
 'Ark Bio Solutions ',
 'ARMI BioFabUSA',
 'Armored Fresh',
 'Arnesale Bioyards',
 'Art of Greens',
 'Arta Bioanalytics',
 'Arte\n  Deli',
 'Artisa',
 'Arummi Foods',
 'Arvesta',
 'Arzeda ',
 'Ascot Valley Foods',
 'Aspyre Foods',
 'Astrid & Aporna',
 'Asymmetrex',
 'Atlantic Fish Company',
 'Atura Proteins',
 'Augason Farms',
 'Austrade, Inc. Food Ingredients',
 "Australia's Own",
 'Australian Plant Proteins',
 'Avafina Organics',
 'Avant Meats',
 'Avebe',
 'Avena Foods Limited',
 'Aviko Rixona',
 'Awevo',
 'Axiom Foods',
 'AzarGen Biotechnologies',
 'Azelis',
 'B.I.F.E',
 'Back of the Yards Algae Sciences',
 'Badische Peptide & Proteine',
 "Bagrry's",
 'Bahama Burger',
 'Barvecue',
 'Basi.Co',
 'Batavo',
 'Bayou Best Foods',
 'BBGI - Fermbox',
 'Be & Cheery / Baicaowei ',
 'Be Better My Friend',
 'Bean Possible',
 'Beano',
 'BeanStalk Brands',
 'Bedda',
 'Bee-io Honey',
 'Before the Butcher',
 'Bega Group',
 'Bel Group',
 'Beleaf',
 "Ben & Jerry's",
 'Bene Meat Technologies',
 'Benecol',
 'BENEO',
 'Benexia',
 'Benji Gourmet ',
 'Berief Food',
 'Berkeley Lab - Advanced Biofuels and Bioproducts Process Development Unit',
 'Betagro Group',
 'BettaF!sh',
 'Bettani Farms',
 'Better Balance',
 'Better Bet',
 'Better Foods',
 'Better Pulse',
 'Better Than Meat',
 'Bettermoo(d)',
 'Beyond Meat',
 'BezMięsny',
 'BI Neutraceuticals',
 'BIC Protein',
 'Bico Group',
 'Biftek.co',
 'Big Mountain Foods',
 'Bigfood',
 'Bilfinger Life Science',
 'Billie Green',
 'Binmei Biotech',
 'Bio Base Europe',
 'Bio-Lead',
 'Bio-Revival',
 'BioBetter',
 'BioBQ',
 'BioBrew',
 'Biocraft',
 'BioCraft Pet Nutrition',
 'BioDalia',
 'BIOFerm',
 'Biográ',
 'Biohifas',
 'BIOinFOOD',
 'Biokraft Foods',
 'Biolab',
 'BioLinker',
 'BiOM Farms',
 'Biomixing',
 'BioMush',
 'Bionet',
 'Biopolis ',
 'BioProcesia',
 'BioRaptor',
 'BioScienz',
 'Biospringer',
 'Biostream International',
 'Biosyntia',
 'BioTech Foods',
 'Biotiful Gut Health ',
 'BioTools',
 'BioTork',
 'Biozentrale',
 'Birds Eye',
 'Bjorg',
 'Black Sheep Foods',
 'Blackbird Foods',
 'BlendTek',
 'Bluana Foods',
 'Blue Diamond Growers',
 'Blue Farm',
 'Blue Mountains Creamery',
 'Blue Tribe Foods',
 'BlueNalu',
 'BLUU Seafood',
 'BOB FoodTech',
 "Bob's Red Mill",
 'Bobeldijk',
 'BOC Sciences',
 'Boca',
 'Boehringer Ingelheim BioXcellence',
 'Boermarke',
 'Boldly',
 'Bolthouse Farms',
 'Bombay Cheese Company',
 'Bonsan Absolutely Vegan',
 'Bonsoy',
 'Booja-Booja',
 'Boston Bioprocess',
 'Brabender',
 'BRAIN-Biocatalysts Life Science Solutions',
 'Bramble',
 'Brannatura',
 'Branston',
 'Break of Dawn',
 'Brecks',
 'Brew Bites',
 'brewbee',
 'Bright Biotech',
 'Bright Planet Pet',
 'Brooklyn Creamery',
 'Brookside Flavors and Ingredients',
 'Brown Foods',
 'BrucePac',
 'Bruno Cell',
 'Bubba Foods',
 'BUCK',
 'Bühler',
 'Bunge',
 'Bunte Burger',
 'Burcon NutraScience Corporation',
 'Burke Corp',
 'Bürkert Fluid Control Systems',
 'Bute Island Foods',
 'BVeg Foods',
 'C-Merak',
 'Cacique',
 'Cado Ice Cream',
 'Caisai Biotechnology',
 'Calabizos',
 'Califia Farms',
 'California Polytechnic State University - FSN Pilot Plant & Labs',
 'Calpro Specialties Private Limited',
 'Cambrium',
 'Camega3',
 'CarboCode',
 'Caremoli USA',
 'Carnéa',
 'Casa del Fermentino',
 'Cascadia Seaweed Corp.',
 'Cashrooom Burger',
 'Cass Materials',
 'Catalyst Creamery',
 'Cathedral City',
 'Cauldron',
 'Cauldron Ferm',
 'Cavi-art',
 'Caviaroli',
 'CBH Qingdao Co.',
 'Cell AgriTech',
 'Cell Craft',
 'Cell Culture Company',
 'Cell Guidance Systems',
 'CELL4FOOD',
 'Cellana',
 'Cellapy Bio',
 'CellCrine',
 'Cellivate Technologies',
 'CellMEAT',
 'CellQua',
 'CellSyn BioSolutions',
 'Celltainer Biotech',
 'CellTec Systems',
 'Cellular Agriculture Limited',
 'Cellura',
 'Cellva',
 'CellX',
 'CellXCell',
 'Century Pacific Foods',
 'Céréal Bio',
 'Cereal Ingredients, Inc. (CII)',
 'CGM Natural Frozen Food',
 'ChainReactor',
 'Charoen Pokphand Foods',
 'Cheese the Queen',
 "Chef Chew's Kitchen",
 'Chemvera Specialities',
 'CHI Foods',
 'Chicago Vegan Foods',
 'ChickP Protein',
 'Chitose Laboratory Corporation',
 'Chokhi Dhani Foods',
 'CHS',
 'Circe',
 'Circular Craft Foods',
 'Cirkulär',
 'CJ Bio',
 'CK Ingredients',
 'Clear Meat',
 'Clearspring',
 'Clever Carnivore',
 'Clextral',
 "Clive's Purely Plants ",
 'ClonBio Group',
 'Coco do Vale',
 'cocojune',
 'Cocoon',
 'Cocos Organic',
 'Cocuus',
 'Conagra',
 'Concepta Ingredients',
 'Condito Foods',
 'Connell',
 'COPAG-Jaouda',
 'Coperion',
 'Coppa della Maga',
 'Copra',
 'Corden Biochem',
 'Cordon Green',
 'Core Biogenesis',
 'CoryPro',
 'Cosaic',
 'Cosmic Bliss',
 'COSUCRA',
 'Cotion Limited',
 'CoYo',
 'CP Kelco',
 'Crackd',
 'Cradle',
 'Crafty Counter',
 "Craig's Vegan Ice Cream ",
 'CreateFoods Canada ',
 'Credo Foods',
 'CREMER Group',
 'CREMER Sustainable Foods',
 'Crummies',
 'CSIRO',
 'Cubiq Foods',
 'Cuíca',
 'CULT Food Science',
 'Cultimate Foods ',
 'Cultivate at Scale',
 'Cultivated Food Labs',
 'Culture Biosciences',
 'Cultured Foods',
 'CULTZYME',
 'Current Foods',
 'Curve Biotech',
 'Cutting Vedge',
 'CV Sciences',
 'Cx Bio',
 'Cysal',
 'CytoNest',
 'Dacsa Group',
 'Dahmes Stainless, Inc. ',
 'Daigas',
 'Dailyfood Group',
 'Dairyland',
 'Daiya Foods ',
 "Dall'albero",
 'Damhert',
 'DaNAgreen',
 'Danone',
 'Darë Vegan Cheese',
 'Daring Foods',
 'Darwin Bioprospecting Excellence',
 'DAVA Foods',
 'Day8',
 'De Nieuwe Melkboer',
 'DE3PBIO',
 'Deco Labs',
 'Dedert',
 'Defined Bioscience',
 'Deligene',
 'Delight Food',
 'Delight Soy',
 'Delishu\xa0',
 'Demolish Foods',
 'dennree',
 'Desi Treat',
 'Detroit Jerky',
 'Devansoy',
 'Developeat',
 'Devigere Biosolutions',
 'Devotion Foods',
 'Dezhou Ruikang Food Co.',
 'Diat Rádisson',
 'Differential Bio',
 'DIL (German Institute of Food Technologies)',
 'Dipasa USA',
 'DiPole Materials',
 'Diverse Farm',
 'DKSH',
 'Dobra Kaloria',
 'Döhler',
 'Dominex',
 'Don Lee Farms',
 'DONGYU USI',
 'DProtein',
 'Dr. Foods',
 "Dr. Praeger's",
 'Dragon Biotechnologies',
 'Dream',
 'Dreamfarm',
 'Driessen Food Extrusion',
 'Drinho',
 'DRYK',
 'Duas Rodas',
 'Ducoco Alimentos',
 'DUG',
 'Dugong',
 'Duoning Biotech',
 'Duplaco',
 'Dutch Organic International Trade',
 'Dutch Structuring Technologies',
 'Dutch Weed Burger',
 'Dynacyte Biosciences',
 'Earth Balance',
 'Eat Curious',
 'Eat Just',
 'Eat Up!',
 'Eat Well Group',
 'EATfunctional',
 'EatKinda',
 'EatVappy',
 'Ebro Ingredients',
 'Eclipse Foods',
 'Eclipse Ingredients',
 'ECO Power',
 'econutri',
 'ECOPACIFIC',
 'Ecotone',
 'Eden Bio',
 'Eden Foods',
 'Edenesque',
 'EdiMembre',
 'EFISHient Protein',
 "Egg'n'Up ",
 'EggField',
 'El Burrito',
 'Elementa Foods',
 "Eleni's Modern Mediterranean",
 'Elián',
 'Elmhurst 1925',
 'Else Nutrition',
 'Emerling International Foods, Inc.',
 'Emsland-Stärke',
 'Enantis',
 'endori',
 'Ener-G Foods',
 'Energaia',
 'enGenes',
 'Ennolys',
 'EnzymoFit',
 'Epoca',
 'Eppendorf',
 'Equinom',
 'ERCOHS',
 'Ergo Bioscience ',
 'ERIDIA',
 'Errigal Bay',
 'Esco Aster',
 'ESPACE Prozess Technologien',
 'Essantis',
 'Essential',
 'Esti',
 'ETH Zürich - Sustainable Food Processing',
 'Euroduna Food Ingredients',
 'Eurosoy',
 'EV Biotech',
 'Ever After Foods',
 'Everbest Soya Bean Products',
 'EverGrain',
 'Evergreen Select',
 'Everything Legendary ',
 'Evlogimeno',
 'Evogene',
 'Evoluter',
 'Evolution Meats',
 'Evolved Foods',
 'Evonext Holdings',
 'Evonik Health Care',
 'Ex-Seed',
 'Extracellular',
 'Extractis',
 'Ezaki Glico',
 'Faba Canada',
 'Fabas',
 'Fable Food Co',
 'Fabumin',
 'FAERM',
 'fairmischt',
 'Farbest Brands',
 'Farm Dairy',
 'Farm Foods USA',
 'Farmer Direct Foods',
 'Fascin8foods',
 'Fattastic Technologies',
 'Fattoria della Mandorla',
 'Faux Gras de GAIA',
 'Fauxmagerie Zengarry',
 'Fazenda Futuro (Future Farm)',
 'Fazer',
 'Feed Your Head Foods',
 'FelsineoVeg ',
 'Fenchem',
 'Fenja BioSolutions',
 'FERM FOOD',
 'Fermaggio',
 'Fermbox Bio',
 'Fermentalg',
 'Fermentia',
 'Fermento Vegano',
 'Fervena',
 'Fiction Foods',
 'Field Roast',
 'Fifth Taste Foods',
 'Filgud',
 'Final Foods',
 'Finally Foods',
 'Finless Foods',
 'Finnebrogue',
 'Finnish Food Factory',
 'Finsbråten',
 'Fioravanti',
 'FirstWave Innovations',
 'Fish Peas',
 'Fishway',
 'Five Suns Foods',
 'FKF Vegan Products',
 'Flavingred Products and Services',
 'Float Foods',
 'Flora Food Group',
 'Flottweg',
 'Flowfood',
 'FoldChanges',
 'Follow Your Heart',
 'FoMu',
 'Food Brewer',
 'Food Heaven',
 'Food Ingredient Technology Co., Ltd.',
 'Food Novelties',
 'Food4You',
 'Foodberry',
 'Foodchem',
 'Foodies',
 'Foodiq',
 'FoodPlant',
 'FoodSquared',
 "Foody's",
 'FoodYoung Labs',
 'Forager Project',
 'Força Foods',
 'Forest Yummy',
 'Fork & Good',
 'Forma Foods',
 'FORMA VEG',
 'Formical',
 'forsea',
 'Fortune  Food',
 'Fotortec ',
 'Four Acre Foods',
 'FourStrain Labs',
 'Framptons',
 'Franklin County Community Development Corporation - Food Processing Center',
 'Fraunhofer Institute for Process Engineering and Packaging',
 'Fredag',
 'Free and Easy',
 'Freely Vegan',
 'Freshcall',
 'Freshwoof',
 'Fresno State University - The Center for Food Science and Nutrition Research Pilot Plant',
 'Freundeskreis',
 'Frías',
 "Frieda's",
 'Friends & Family Pet Food Company',
 'FrieslandCampina',
 'FUDI Protein',
 'Fuji Oil Co.',
 'Fumacense\n  Alimentos',
 "Fungu'it",
 'Funny Nani',
 'Fysh Foods',
 'G.S. Gelato',
 'Galactic',
 'Galpao Cucina',
 'Gardein',
 'Garden Gourmet',
 'Garuda International, Inc.',
 'Gavan',
 'GEA',
 'Geb Impact Technology',
 'Gelatex Technologies',
 'GeneFerm',
 'Genesea',
 'Genesis Biosciences',
 'Genexis Biotech',
 'GenScript',
 'Genuine Taste',
 'Gimme Sabor',
 'Ginkgo Bioworks',
 'Givaudan ',
 'GK Foods',
 'Glanbia Nutritionals',
 'Glebe Farm Foods',
 'Gold&Green Foods',
 'Golden Fields',
 'Golden Platter Foods',
 'Goldie Lox',
 'Golfera',
 'Good & Humble',
 'Good Carma Foods',
 'Good Hemp',
 'Good Karma Foods',
 'GOOD Meat',
 'Good Mylk Co.',
 'GOOD PLANeT Foods',
 'GoodDot',
 'Goodfoods',
 'GoodMills Innovation',
 'GoodMorning Bio Industries',
 'Goodness Plant',
 'Gosh!',
 'Goshen Alimentos',
 'GOURMEY',
 'GPV Foods',
 'Grabenord ',
 'Grainstone',
 'Granovita',
 'Grashka',
 'Grassa',
 'Grater Goods',
 'Green Boy Group',
 'Green Cuisine',
 'Green Go',
 'Green Legend',
 'Green Rebel Foods',
 'Green Source Organics',
 'Green Wolf Foods',
 'Green-On',
 'Greenest',
 'GreenFood50',
 'GREENFORCE',
 'GreenLab ',
 'Greenster',
 'GreenVie',
 'Greenwise',
 'Greenyard',
 'Gremount International Company',
 'Griffith Foods ',
 'Grillies',
 'Grin Grin Foods',
 'GrowMeat',
 'Growthwell Foods',
 'Grupo Nutresa',
 'Gushen Biological Technology Group Co.',
 'Gusmer Enterprises, Inc. ',
 ...]

In [51]:
nomatch = company_list[~company_list["Cleaned-up Name"].values.isin(company_database['Company'])]
nomatch = nomatch.drop_duplicates(subset="Cleaned-up Name")

In [8]:
df["assignee_names"]

0      [VISHWAKARMA INSTITUTE OF TECHNOLOGY]
1                     [NEW SCHOOL FOODS INC]
2                                [PALEO B V]
3                             [UNIV QINGDAO]
4                           [UNIV SOUTHWEST]
                       ...
233                              [Mynu Corp]
234                 [Umami Bioworks Pte Ltd]
235                       [Donaldson Co Inc]
236                            [Senara GmbH]
237                   [PRAIRIE AQUATECH LLC]
Name: assignee_names, Length: 238, dtype: object

In [9]:
name_map = dict(zip(company_list['Name'], company_list['Cleaned-up Name']))

In [ ]:
df['assignee_names_cleaned'] = df['assignee_names'].apply(
    lambda x: name_map.get(x, x) if not isinstance(x, (list, np.ndarray)) 
              else [name_map.get(n, n) for n in x]
)

In [75]:
df['assignee_names_cleaned'] = df['assignee_names_cleaned'].apply(
    lambda names: [n.upper() for n in names] if isinstance(names, list) else names
)

In [76]:
import unicodedata

def normalize(s):
    return unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')

def match_company(names, companies, cutoff=90):
    companies_normalized = [normalize(c) for c in companies]
    
    def get_match(n):
        result = process.extractOne(
            normalize(n), companies_normalized,
            scorer=fuzz.WRatio,
            processor=utils.default_process,
            score_cutoff=cutoff
        )
        if result:
            match, score, idx = result
            original_match = companies[idx]  # get original with accents
            if len(original_match) >= len(n) * 0.5:
                return original_match
        return n
    
    if isinstance(names, (list, np.ndarray)):
        return [get_match(n) for n in names]
    return names

df['assignee_names_matched'] = df['assignee_names_cleaned'].apply(
    lambda x: match_company(x, companies)
)

In [68]:
df['assignee_names_cleaned']

0      [VISHWAKARMA INSTITUTE OF TECHNOLOGY]
1                     [NEW SCHOOL FOODS INC]
2                                    [paleo]
3                             [UNIV QINGDAO]
4                           [UNIV SOUTHWEST]
                       ...
233                              [Mynu Corp]
234                 [Umami Bioworks Pte Ltd]
235                       [Donaldson Co Inc]
236                            [Senara GmbH]
237                                 [Houdek]
Name: assignee_names_cleaned, Length: 238, dtype: object

In [80]:
df[df['assignee_names_cleaned'] != df['assignee_names_matched']]

,id,title,abstract,application_number,assignee_cities,assignee_countries,assignee_names,family_count,family_id,filing_status,...,times_cited,year,cpc,current_assignee_names,publications,proba_scope,pred_combined,pred_pillar,assignee_names_cleaned,assignee_names_matched
1,ZA-202311713-B,"PROCESS FOR PRODUCING COOKABLE, FIBROUS MEAT A...",The present disclosure provides a process for ...,ZA2023/11713,"[{'id': '6167865', 'name': 'Toronto'}]",[],[NEW SCHOOL FOODS INC],13,84104569,N/A,...,0,2023,"[A23J3/24, A23V2002/00, A23J3/18, A23J3/06, A2...",<NA>,<NA>,0.726477,in,PB,[NEW SCHOOL FOODS INC],[New School Foods]
2,ZA-202306560-B,MEAT SUBSTITUTE COMPRISING ANIMAL MYOGLOBIN,Described herein is a meat substitute or food ...,ZA2023/06560,"[{'id': '2799397', 'name': 'Diest'}]",[],[PALEO B V],20,79927393,N/A,...,0,2023,"[A23J3/26, C07K14/805, A23L13/424, A23L33/17, ...",<NA>,<NA>,0.929412,in,F,[PALEO],[paleo]
7,ZA-202406920-B,FOOD PRODUCTS FROM ROOT VEGETABLES,A hard cheese analogue may be produced from a ...,ZA2024/06920,<NA>,[],[MCCAIN FOODS LTD],16,85704456,N/A,...,0,2024,"[A23L19/13, A23L19/09, A23L19/12, A23L19/15, A...",<NA>,<NA>,0.965656,in,PB,[MCCAIN FOODS LTD],[McCain Foods]
12,ZA-202401888-B,MICROBIAL-BASED PROCESS FOR IMPROVED QUALITY P...,The present invention describes a bio-based pr...,ZA2024/01888,"[{'id': '5226534', 'name': 'Brookings'}]",[],[PRAIRIE AQUATECH LLC],27,78845797,N/A,...,0,2024,"[A23J3/16, C12R2001/645, A23K20/147, Y02A40/81...",<NA>,<NA>,0.771990,in,F,[HOUDEK],[Houdek]
14,ZA-202400323-B,A METHOD FOR MANUFACTURING A FOOD PRODUCT FROM...,A method for manufacturing a food product from...,ZA2024/00323,<NA>,[],[USARIUM INC],14,82802741,N/A,...,0,2024,"[A23J3/16, A23J3/227, A23J3/26, A23J3/20, Y02P...",<NA>,<NA>,0.973452,in,F,[PLANETARIANS],[Planetarians]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,WO-2025129359-A1,EDIBLE SCAFFOLDS AND FORMULATIONS FOR CULTIVAT...,Cell culture scaffolds suitable for cultivated...,CA2024/051725,<NA>,[],[Meatleo Inc],1,96136087,Application,...,0,2024,"[C12N2533/78, C12N5/0068, C12N5/0658, A23L13/0...",[Meatleo Inc],"[{'doi': '10.1016/j.biomaterials.2022.121659',...",0.849341,in,CM,[MEATLEO INC],[Meatleo]
233,WO-2025127703-A1,ALTERNATIVE MEAT COMPRISING FUNGAL MYCELIUM AN...,The present specification relates to an altern...,KR2024/020267,<NA>,[],[Mynu Corp],3,96057899,Application,...,0,2024,"[A23L13/00, A23L31/00, A23K10/16, C12N1/14]",[Mynu Corp],<NA>,1.000000,in,F,[MYNU CORP],[Mynu Corp]
234,WO-2025126155-A1,COMPOSITIONS AND METHODS FOR PRODUCTION OF EDI...,Edible scaffolds prepared from plant protein a...,IB2024/062661,<NA>,[],[Umami Bioworks Pte Ltd],1,96056597,Application,...,0,2024,"[A23L13/00, A23J3/18, A23J3/20, A23J3/14, A23J...",[Umami Bioworks Pte Ltd],<NA>,0.947522,in,CM,[UMAMI BIOWORKS PTE LTD],[Umami Bioworks]
236,WO-2025120607-A1,CELL-CULTIVATED MILK FOR CONFECTIONERY AND DAI...,Cell-cultured milk generated in vitro in a rea...,IB2024/062345,<NA>,[],[Senara GmbH],1,94278617,Application,...,0,2024,"[A23C23/00, A23C9/20, C12N2510/00, C12M25/10, ...",[Senara GmbH],<NA>,0.810661,in,CM,[SENARA GMBH],[Senara]
237,ZA-202213273-B,MICROBIAL-BASED PROCESS FOR IMPROVED QUALITY P...,The present invention describes a bio-based pr...,ZA2022/13273,"[{'id': '5226534', 'name': 'Brookings'}]",[],[PRAIRIE AQUATECH LLC],27,78845797,N/A,...,0,2022,"[A23K50/80, C12P21/06, A23J3/16, A23J1/148, A2...",<NA>,<NA>,0.771990,in,F,[HOUDEK],[Houdek]

In [81]:
df.head()

,id,title,abstract,application_number,assignee_cities,assignee_countries,assignee_names,family_count,family_id,filing_status,...,times_cited,year,cpc,current_assignee_names,publications,proba_scope,pred_combined,pred_pillar,assignee_names_cleaned,assignee_names_matched
0,ZA-202501977-B,A SOILLESS FARMING SYSTEM,The present invention relates to a soilless fa...,ZA2025/01977,"[{'id': '1259229', 'name': 'Pune'}]",[],[VISHWAKARMA INSTITUTE OF TECHNOLOGY],1,97493629,N/A,...,0,2025,<NA>,<NA>,<NA>,0.817097,in,PB,[VISHWAKARMA INSTITUTE OF TECHNOLOGY],[VISHWAKARMA INSTITUTE OF TECHNOLOGY]
1,ZA-202311713-B,"PROCESS FOR PRODUCING COOKABLE, FIBROUS MEAT A...",The present disclosure provides a process for ...,ZA2023/11713,"[{'id': '6167865', 'name': 'Toronto'}]",[],[NEW SCHOOL FOODS INC],13,84104569,N/A,...,0,2023,"[A23J3/24, A23V2002/00, A23J3/18, A23J3/06, A2...",<NA>,<NA>,0.726477,in,PB,[NEW SCHOOL FOODS INC],[New School Foods]
2,ZA-202306560-B,MEAT SUBSTITUTE COMPRISING ANIMAL MYOGLOBIN,Described herein is a meat substitute or food ...,ZA2023/06560,"[{'id': '2799397', 'name': 'Diest'}]",[],[PALEO B V],20,79927393,N/A,...,0,2023,"[A23J3/26, C07K14/805, A23L13/424, A23L33/17, ...",<NA>,<NA>,0.929412,in,F,[PALEO],[paleo]
3,ZA-202500303-B,AN ISOLATION AND CULTURE METHOD AND APPLICATIO...,The present invention belongs to the field of ...,ZA2025/00303,"[{'id': '1797929', 'name': 'Qingdao'}]",[],[UNIV QINGDAO],3,93807478,N/A,...,0,2025,"[C12N5/0653, C12N5/0668, C12N5/0654, C12N5/068...",<NA>,<NA>,0.722953,in,CM,[UNIV QINGDAO],[UNIV QINGDAO]
4,ZA-202500087-B,RESEARCH METHOD FOR SKM-EXOS THAT PROMOTE PROL...,The invention discloses a research method for ...,ZA2025/00087,"[{'id': '1814906', 'name': 'Chongqing'}]",[],[UNIV SOUTHWEST],2,91602588,N/A,...,0,2025,"[G01N33/5061, G01N21/6458, C12Q1/6876, G01N33/...",<NA>,<NA>,0.640767,in,CM,[UNIV SOUTHWEST],[UNIV SOUTHWEST]

In [57]:
## Check labels
df_training = pd.read_csv("../../Patents/Patents_Data/patents_subest_for_pipeline_testing2.csv")
df_training["subpillarT"] = df_training["subpillar"]
df_training["research_categoryT"] = df_training["research_category"]
df_training["endproductT"] = df_training["endproduct"]
df_training["ingredientT"] = df_training["ingredient"]

In [58]:
df_training = df_training[["id", "scope", "pillar", "subpillarT", "research_categoryT", "endproductT", "ingredientT"]]

In [22]:
len(df_training)

820

In [59]:
df_comb = pd.merge(df, df_training, on = "id")

In [53]:
len(df_comb)

525

In [60]:
df_comb

,id,family_id,application_number,title,abstract,cpc,publication_year,jurisdiction,date_dimensions,date_ML,...,research_category,end_product,ingredient,subpillar,scope,pillar,subpillarT,research_categoryT,endproductT,ingredientT
0,KR-20260058202-A,87847814,KR1020267005189,Powdered food emulsion composition containing ...,The present invention relates to a powdered fo...,"['A23P10/40', 'A23L2/39', 'A23C11/06', 'A23C11...",2026,KR,260710,260710,...,End product formulation,Cross-cutting,"Emulsions, gels, and binders",NaN,in,PB,NaN,Ingredient optimisation,Milk and milk proteins,"Emulsions, gels, and binders"
1,WO-2025074118-A1,93119608,GB2024/052562,METHODS FOR INCREASING THE FAT CONTENT OF A CELL,Described herein are novel methods for increas...,"['C12N5/0653', 'C12N2501/01', 'C12N2527/00']",2025,WO,260710,260710,...,Cell line development,Meat,Fats and oils,NaN,in,CM,NaN,Cell line development,Meat,Fats and oils
2,EP-4638706-A2,89542141,EP23838012.5,NANOFIBROUS SCAFFOLD FOR CELL CULTURING,The present invention relates to a method for ...,"['C12N2513/00', 'C12M33/00', 'C12M25/02', 'C12...",2025,EP,260710,260710,...,Scaffolding,Agnostic,N/A,NaN,in,CM,NaN,Scaffolding,Meat,NaN
3,PL-247657-B1,91227479,PL442891,Method for producing instant vegetable steaks ...,The subject of the application is an instant v...,"['A23L19/00', 'A23L33/125', 'A23L33/105', 'A23...",2025,PL,260710,260710,...,End product formulation,Meat,N/A,NaN,in,PB,NaN,End product formulation,Meat,NaN
4,US-20250000129-A1,83692816,US18690539,USE OF LEGUMINOUS STARCH AND ITS CROSS LINKED ...,The present invention is relative to the use o...,"['A23L29/219', 'A23L13/426', 'A23J3/227', 'A23...",2025,US,260710,260710,...,End product formulation,Meat,"Emulsions, gels, and binders",NaN,in,PB,NaN,Texturization methods,Meat,"Emulsions, gels, and binders"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520,US-20210309723-A1,70469698,US17287905,RECOMBINANT PRODUCTION OF A COLLAGEN PEPTIDE P...,The present invention relates to a method for ...,"['A61K38/39', 'A61K38/00', 'A61Q19/00', 'A61Q5...",2021,US,260710,260710,...,Target molecule selection,Agnostic,"Emulsions, gels, and binders",PF,in,F,NaN,Target molecule selection,Cross-cutting,"Emulsions, gels, and binders"
521,EP-4750886-A1,87517248,EP24752137.0,METHOD OF GENERATING ADIPOCYTES,The invention relates to methods of generating...,"['C07K14/4702', 'C12N2501/115', 'G01N33/5044',...",2026,EP,260710,260710,...,Cell line development,Agnostic,N/A,NA,in,CM,NaN,Cell line development,Meat,Fats and oils
522,JP-2026504736-A,85035928,JP2025536188,Culture method,The present invention relates to a method for ...,"['C12N5/0062', 'C12N5/0075', 'C12N2509/00', 'C...",2026,JP,260710,260710,...,Bioprocess design,Agnostic,N/A,NA,in,CM,NaN,Bioprocess design,Meat,NaN
523,CN-118434289-A,79316900,CN202280083734.3,Method for improving processing characteristic...,The present invention relates to protein compo...,"['C12N9/63', 'A61K9/14', 'C08J2389/00', 'A23K2...",2024,CN,260710,260710,...,Ingredient optimisation,Cross-cutting,"Isolates, concentrates, and flours",NA,in,CC,NaN,Ingredient optimisation,Agnostic,"Isolates, concentrates, and flours"
524,DK-181968-B1,89452591,DKPA202270619,CHOCOLATE COMPOSITION COMPRISING OMEGA-3-FATTY...,The present invention relates to a chocolate p...,"['A23G1/32', 'A23G1/48', 'A23G1/36']",2025,DK,260710,260710,...,End product formulation,"Chocolate, desserts, and confectionery",N/A,NA,in,PB,NaN,End product formulation,"Chocolate, desserts, and confectionery",Fats and oils

In [61]:
df_comb["categoryC"] = df_comb["research_category"] == df_comb["research_categoryT"]
df_comb["endproductC"] = df_comb["end_product"] == df_comb["endproductT"]
df_comb["ingredientC"] = df_comb["ingredient"] == df_comb["ingredientT"]
df_comb["subpillarC"] = df_comb["subpillar"] == df_comb["subpillarT"]

In [41]:
df_comb.to_csv("../../Patents/Patents_Data/Training_labels_results.csv")

In [67]:
db.close()